### ISSUE TITLE
Add slider for number of items that can be stored in a storage unit

### ISSUE THREAD

**Issue by Mhburg** [lilwhitemouse/RimWorld-LWM.DeepStorage#71] opened 2020-05-01 23:40 UTC
Just to pick up where we left.

One complication I can think of is that pawns are hauling to storage when a player change the setting. Can we allow the storage overflow temporarily, then put a hauling job on those extra things?

**Comment by lilwhitemouse** [comment] 2020-05-02 00:45
Duplicate of #17

**Closed by lilwhitemouse** 2020-05-02 00:45 UTC
